import { ChallengeCard } from "./data";

export const challengeCards: ChallengeCard[] = [
  {
    day: 1, title: "Called to Go", theme: "Joyful Connections",
    worshipNote: "Praise opens our hearts to God's presence",
    praiseScripture: "Come, let us sing to the Lord! Let us shout joyfully to the Rock of our salvation. — Psalm 95:1-2",
    prayer: "Father, As I start today, I want to thank You for calling me to share the Gospel with others. I believe in what Your Word says in Mark 16:15 that I am meant to spread the message of hope and salvation. I'm asking for a fresh outpouring of the Holy Spirit. Fill me with courage as I step out in faith, and remind me that I'm never alone because You are always with me. As I visit parks and coffee shops, help me to be open to the people I encounter. Help me to share my story with love and boldness. I pray for meaningful conversations that will plant seeds of faith, hope, and life in others. Thank You for the privilege of being Your messenger! In Jesus' name!",
    keyScripture: "\"Go into all the world and preach the gospel to all creation.\" — Mark 16:15",
    dailyReading: "Matthew 1-2",
    encouragement: "I am with you always. Today, don't worry about what to say, open your mouth, and I will fill it. Step out in faith.",
    challenge: "Share your testimony with someone at a local park or coffee shop.",
    locationSuggestions: "Parks, coffee shops, outdoor benches.",
    groupActivity: "Invite a friend to join you and share testimonies together while meeting people.",
    reflections: ["What was the biggest challenge today?", "What did you enjoy most about sharing your story?"],
    prayingForSick: "Lay your hands on the sick, believing that God's power flows through you! Don't hesitate—step out in faith!"
  },
  {
    day: 2, title: "Speaking with Boldness", theme: "Courageous Conversations",
    worshipNote: "Thanking God helps us recognize His blessings in and around our lives",
    praiseScripture: "Let all that I am praise the Lord; with my whole heart, I will praise His holy name. — Psalm 103:1",
    prayer: "Dear Lord, Today, I am full of hope and excitement! Fill me with the courage to speak Your Word boldly. Thank You for giving me everything I need to follow my purpose. Help me to notice the opportunities to share Your love and truth with those around me. Give me the boldness to reach out to someone in need, even in a parking lot, and offer to pray for them. I lift up those who are struggling and feeling lost. Help me to pray boldly and with authority, commanding sickness and pain to leave in Jesus' name. Thank You for letting me be Your voice. In Jesus' powerful name!",
    keyScripture: "Now, Lord, consider their threats and enable your servants to speak your word with great boldness. — Acts 4:29",
    dailyReading: "Matthew 3-4",
    encouragement: "Step out in boldness today. My Spirit has infused you with power and courage to fulfill what I've called you to do.",
    challenge: "Approach someone in a parking lot and offer to pray for them.",
    locationSuggestions: "Grocery stores, shopping plazas.",
    groupActivity: "Gather with friends to practice sharing stories of faith and a quick testimony about Jesus to build confidence.",
    reflections: ["How did you feel before, during, and after you stepped out in faith?", "How did God help you conquer any fear that tried to hold you back?"],
    prayingForSick: "Pray with authority, commanding sickness to leave in Jesus' name! Stand firm in your faith and declare healing over every ailment."
  },
  {
    day: 3, title: "Ambassadors of Christ", theme: "Representing His Love",
    worshipNote: "Worship brings joy, peace, and victory into our lives",
    praiseScripture: "Sing to the Lord, all you godly ones! Praise His holy name. — Psalm 30:4",
    prayer: "Lord, Thank You for the honor of being called Your ambassador. Your Word in 2 Corinthians 5:20 reminds me that You speak through me. Today, I pray for the boldness to share Jesus with those I meet in malls, stores, and anywhere else I go. Let Your Word flow through me, bringing life and hope to everyone around. If I feel hesitant or unsure, remind me of Your promise to never leave me. I also pray for those in need of healing today. Thank You for the privilege of being Your representative. In Jesus' name!",
    keyScripture: "We are therefore Christ's ambassadors, as though God were making his appeal through us. — 2 Corinthians 5:20",
    dailyReading: "Matthew 5-6",
    encouragement: "You are My ambassador; speak confidently, knowing My word will flow through you as you open your mouth.",
    challenge: "Share about Jesus with someone at a mall or shopping center.",
    locationSuggestions: "Shopping malls, retail stores.",
    groupActivity: "Team up with friends to write notes with scriptures and encouragement to hand out as you speak to people.",
    reflections: ["Did you sense any hesitation before taking a step of faith?", "How did you experience God's presence with you in that moment?"],
    prayingForSick: "Speak healing over people; remember, it's God's power, not yours! Declare His word knowing that He brings restoration and wholeness."
  },
  {
    day: 4, title: "Walking by Faith, Not by Sight", theme: "Trusting God's Plan",
    worshipNote: "Starting the day with praise sets the tone and shifts the atmosphere",
    praiseScripture: "I will praise the Lord at all times. I will constantly speak His praises. — Psalm 34:1",
    prayer: "Father, Today, I ask You to stretch my faith and help me walk confidently, even if I don't see immediate results. I commit to obeying Your Word and being sensitive to the leading of the Holy Spirit. Give me favor as I visit hospitals or nursing homes, allowing me to pray for the sick. Remind me that it's You who moves and confirms Your Word as I pray and lay hands on the sick. Thank You for touching and healing lives and for being a faithful God who honors our steps of faith. In Jesus' name!",
    keyScripture: "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. — Hebrews 11:6",
    dailyReading: "Matthew 7-8",
    encouragement: "Even if you don't see immediate results, trust that I am working.",
    challenge: "Go to a hospital or nursing home and ask to pray for the sick.",
    locationSuggestions: "Hospitals, nursing homes.",
    groupActivity: "Share or listen to faith and miracle testimonies with friends to encourage one another and build your faith.",
    reflections: ["What challenges did you face today?", "How did you see God move?"],
    prayingForSick: "Thank God for the healing, whether you see it immediately or not. Your gratitude opens the door for His power to work!"
  },
  {
    day: 5, title: "The Power of Prayer", theme: "Prayer Warriors",
    worshipNote: "Worship strengthens our relationship with God and our sensitivity to the Holy Spirit",
    praiseScripture: "Sing psalms and hymns and spiritual songs among yourselves, and making music to the Lord in your hearts. — Ephesians 5:19",
    prayer: "Father, I thank You for the gift of prayer and for being my stronghold. Remind me of the authority You've given me. Today, I'm stepping out in faith, looking for someone in need, whether at a bus stop or in a waiting area. Fill me with courage and compassion to bring hope to those who feel tired or lost. I lift up everyone who is sick today, fully believing in Your healing power. Your promises are true. In Jesus' name!",
    keyScripture: "The prayer of a righteous person is powerful and effective. — James 5:16",
    dailyReading: "Matthew 9-10",
    encouragement: "Your prayers are powerful; don't underestimate what I can do through you.",
    challenge: "Pray for someone at a bus stop or waiting area.",
    locationSuggestions: "Bus stops, train stations, waiting areas.",
    groupActivity: "Organize a prayer walk in your community.",
    reflections: ["How did you see God work through your prayers?", "What surprised you today?"],
    prayingForSick: "Pray boldly, knowing that God is faithful to His promises."
  },
  {
    day: 6, title: "The Heart of Compassion", theme: "Serving Others",
    worshipNote: "Thankfulness opens doors to the miraculous and strength through joy",
    praiseScripture: "Always be full of joy in the Lord. I say it again—rejoice! — Philippians 4:4",
    prayer: "Father, As I start this day, I thank You for the gift of life. Fill me with compassion so I can reflect Your love to everyone I meet. Help me see the weary and the lost through Your eyes. Today, I commit to reaching out to someone in need. Give me the boldness to approach them with kindness and offer to pray with them. I trust in Your power to heal and restore. Let Your heart be evident in and through me today! In Jesus' name, amen!",
    keyScripture: "When he saw the crowds, he had compassion on them, because they were harassed and helpless, like sheep without a shepherd. — Matthew 9:36",
    dailyReading: "Matthew 11-12",
    encouragement: "Today, let your heart be moved with compassion for those around you. See them as I see them. Freely you have received, freely give!",
    challenge: "Engage with someone who looks troubled or lonely at a bus stop, train station, or public bench and offer to pray with them.",
    locationSuggestions: "Bus stops, train stations, public benches.",
    groupActivity: "Volunteer as a group at a soup kitchen or local charity.",
    reflections: ["How did seeing people through Jesus' eyes change your approach today?", "What moved you the most during your conversations?"],
    prayingForSick: "Pray for those who are weary and need healing, knowing that My heart is reflected through your compassion."
  },
  {
    day: 7, title: "Healing the Sick", theme: "Healing",
    worshipNote: "Praise invites the presence of God and causes His greatness and power to go before us",
    praiseScripture: "Yet you are holy, enthroned on the praises of Israel. — Psalm 22:3",
    prayer: "Father, I thank You for the authority You've given me to heal and set others free, just as Your Word promises in Matthew 10:8. Today, I step out in faith, trusting in Your will to heal and set free everyone ensnared by sickness or oppression. Lead me to those in need. Fill me with compassion and boldness. Let my prayers be sincere, full of faith, and in line with Your Word. I want to see signs and wonders follow everywhere I go. Thank You for using me as a vessel to shine Your light. In Jesus' name, amen!",
    keyScripture: "Heal the sick, raise the dead, cleanse those who have leprosy, drive out demons. Freely you have received; freely give. — Matthew 10:8",
    dailyReading: "Matthew 13-14",
    encouragement: "Step out in faith today, trusting in My power to heal. I am the same yesterday, today, and forever.",
    challenge: "Visit a community center or public park and pray for those who are physically sick or struggling.",
    locationSuggestions: "Community centers, parks.",
    groupActivity: "Hold a healing and miracle prayer session with your friends and pray for people.",
    reflections: ["Did you feel stirred in your spirit when praying for healing?", "How did God show up when you took that step of faith in prayer?"],
    prayingForSick: "Pray with bold faith and precision! Declare that God would touch them and restore their health!"
  },
  {
    day: 8, title: "Sharing Hope", theme: "Hope Bearers",
    worshipNote: "Worship aligns us with the heart, mind, and Spirit of God",
    praiseScripture: "Let us offer through Jesus a continual sacrifice of praise to God, proclaiming our allegiance to His name. — Hebrews 13:15",
    prayer: "Father, I thank You for the hope You've placed in my heart, just like 1 Peter 3:15. This hope isn't just for me; it's meant to be shared. Today, I commit to being a vessel of Your hope. Whether I'm in a store, at a coffee shop, or at an event, help me engage in conversations that matter. Give me the right words so that my story touches hearts. I also lift up those who are sick today. Let my prayers bring hope, comfort, and strength. Thank You for the privilege of sharing Your hope with the world. In Jesus' name!",
    keyScripture: "Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect. — 1 Peter 3:15",
    dailyReading: "Matthew 15-16",
    encouragement: "Today, be ready to share the hope that is within you. You carry My life and light wherever you go, like a city set on a hill.",
    challenge: "Strike up a conversation with someone waiting in line and share how Jesus has given you hope.",
    locationSuggestions: "Retail stores, coffee shops, public events.",
    groupActivity: "Create care packages with encouraging notes to distribute, including a way to reach you.",
    reflections: ["How did sharing your hope make an impact?", "What surprised you about the interaction?"],
    prayingForSick: "Pray, believing that God's promises are true and His power is at work through you."
  },
  {
    day: 9, title: "The Power of Testimony", theme: "Triumph in Christ!",
    worshipNote: "Thanking God builds up our faith and trust in Him",
    praiseScripture: "Praise the Lord! How good to sing praises to our God! How delightful and how fitting! — Psalm 147:1",
    prayer: "Father, I thank You today, remembering that we overcome by the blood of the Lamb and the word of our testimony. As I get ready to share my story with someone new, I ask for Your guidance and courage. Let my testimony be a powerful tool to draw people closer to You. Fill me with love and compassion, and give me the right words. I also lift up those who are sick. May my testimony stir up their faith. Thank You for the gift of my testimony. In Jesus' name, amen!",
    keyScripture: "They triumphed over him by the blood of the Lamb and by the word of their testimony. — Revelation 12:11",
    dailyReading: "Matthew 17-18",
    encouragement: "Your testimony carries power. Share what I have done in your life and watch how it opens their hearts.",
    challenge: "Tell someone you've never met about a personal miracle or answered prayer that has changed your life.",
    locationSuggestions: "Public libraries, gyms, civic centers, coffee shops.",
    groupActivity: "Host a testimony night where friends and people can share about what God has done.",
    reflections: ["How did sharing your testimony affect the other person?", "What did you learn about the power of sharing your story?"],
    prayingForSick: "Use your testimony to build faith in those who need healing. Share it and pray boldly!"
  },
  {
    day: 10, title: "Bold Faith in Action", theme: "Faith Moves!",
    worshipNote: "Praise lifts our spirit and breaks the power of the enemy off our life",
    praiseScripture: "Everything on earth will worship You; they will sing Your praises, shouting Your name in glorious songs. — Psalm 66:4",
    prayer: "Father, I thank You for today and the excitement I feel in my spirit. Fill me with boldness, Lord. As I walk through marketplaces, malls, or wherever You lead me, guide me to the people who need a touch from You. Give me the courage to pray for them, to speak life into their situations. I believe that as I step out in faith, You will show up in power. Thank You for the privilege of sharing the message of hope and healing through Jesus Christ. In Jesus' name!",
    keyScripture: "In the same way, faith by itself, if it is not accompanied by action, is dead. — James 2:17",
    dailyReading: "Matthew 19-20",
    encouragement: "Put your faith into action today. Step out and watch Me work. You will see miracles unfold as you align your heart with My purpose!",
    challenge: "Pray for someone in a public setting (like a marketplace or mall) without hesitation or fear.",
    locationSuggestions: "Markets, shopping malls, busy streets.",
    groupActivity: "Create a \"Boldness Board\" with encouragements and goals that provide accountability and build your faith.",
    reflections: ["How did your faith feel as you prayed?", "How did God move when you stepped out?"],
    prayingForSick: "Pray full of expectation, knowing that God honors your step of faith."
  },
  {
    day: 11, title: "Speaking Life", theme: "Beacon of Light!",
    worshipNote: "Worship helps us shift our focus from our worries to the One who is above them all",
    praiseScripture: "My mouth is filled with Your praise, declaring Your splendor all day long. — Psalm 71:8",
    prayer: "Father, I thank You for today, for the breath in my lungs, and the opportunity to serve You. Today, I go out with boldness, filled with Your Spirit. Fill me with wisdom and the right words that will pierce hearts. Give me eyes to see the needs around me. Let every conversation be filled with Your grace. Let my words carry the weight of Heaven, bringing hope, healing, and life. Today, I expect to see miracles. In Jesus' name!",
    keyScripture: "The tongue has the power of life and death, and those who love it will eat its fruit. — Proverbs 18:21",
    dailyReading: "Matthew 21-22",
    encouragement: "Speak life over others today. Your words carry My power to encourage, heal, and restore.",
    challenge: "Find someone who looks discouraged or sad, and encourage them by speaking a word of life and hope into their situation.",
    locationSuggestions: "Bus stops, cafes, parks.",
    groupActivity: "Share uplifting scriptures with people in your community. Hand out scriptures written on cards and pray for each person.",
    reflections: ["How did people respond to your words?", "Did you sense God using your words to uplift and encourage?"],
    prayingForSick: "Speak healing, and speak life over the sick, declaring God's promises over them."
  },
  {
    day: 12, title: "Love in Action", theme: "Love is a Verb!",
    worshipNote: "Thankfulness develops a grateful heart",
    praiseScripture: "I will thank You, Lord, with all my heart; I will tell of all Your wonderful deeds. — Psalm 9:1",
    prayer: "Father, Thank You for reminding me that love is what truly shows I belong to You, as it says in John 13:35. Help me to show Your love through all my actions today. Lead me to opportunities for small acts of kindness, like buying someone a coffee, helping with groceries, or simply sharing a smile. I lift up all who are sick. Open doors for me to share the Gospel. Thank You for this opportunity. In Jesus' name!",
    keyScripture: "By this everyone will know that you are My disciples, if you love one another. — John 13:35",
    dailyReading: "Matthew 23-24",
    encouragement: "Let My love shine through your actions today. You are My hands and feet.",
    challenge: "Do a random act of kindness (buy someone a coffee, help with groceries, etc.) and share about Jesus' love.",
    locationSuggestions: "Coffee shops, grocery stores, public transport.",
    groupActivity: "Start the \"Acts of Kindness Bingo Challenge\" with friends or family.",
    reflections: ["How did showing love open doors for sharing the Gospel?", "What did you learn about love in action?"],
    prayingForSick: "Pray with a heart of compassion, seeing them as God sees them."
  },
  {
    day: 13, title: "Following the Holy Spirit", theme: "Spirit-Led Living!",
    worshipNote: "Praise gives us God's perspective",
    praiseScripture: "He has given me a new song to sing, a hymn of praise to our God. Many will see what He has done and be amazed. — Psalm 40:3",
    prayer: "Dear Father, Thank You for the gift of the Holy Spirit. Today, I declare that I am guided by Your Spirit and will walk confidently in the purpose You have for me, just like Romans 8:14. Help me to be sensitive to Your leading. Lead me to someone who needs encouragement or prayer. I pray for those who are sick and need healing. Lord, guide my steps today! In Jesus' name!",
    keyScripture: "For those who are led by the Spirit of God are the children of God. — Romans 8:14",
    dailyReading: "Matthew 25-26",
    encouragement: "Be sensitive to My Spirit today. I will guide you to specific people.",
    challenge: "Ask the Holy Spirit to lead you to someone specific to share or pray with today.",
    locationSuggestions: "Anywhere—follow the Spirit's leading!",
    groupActivity: "Share experiences of following the leading of the Holy Spirit with one another.",
    reflections: ["How did you sense the Holy Spirit leading you today?", "What happened when you followed His promptings?"],
    prayingForSick: "Let the Holy Spirit guide you as you pray, listening for His direction."
  },
  {
    day: 14, title: "Breaking Fear", theme: "Courageous Faith!",
    worshipNote: "Worship is a way to express our love for God",
    praiseScripture: "Sing to the Lord, for He has done wonderful things. Make known His praise around the world. — Isaiah 12:5",
    prayer: "Father, As I begin this day, I am holding onto Your promise in 2 Timothy 1:7, knowing You haven't given me a spirit of fear but of power, love, and a sound mind. Today, I'm asking You for strength and boldness as I step out in faith. If any fear tries to grip me, remind me that it doesn't come from You. Thank You for being my source and strength. In Jesus' mighty name! Amen!",
    keyScripture: "For God has not given us a spirit of fear, but of power and of love and of a sound mind. — 2 Timothy 1:7",
    dailyReading: "Matthew 27-28",
    encouragement: "Fear is not from Me. Step out boldly today, knowing I have given you power and love.",
    challenge: "Share your faith in a setting where you would normally feel afraid or hesitant.",
    locationSuggestions: "Crowded places, public squares.",
    groupActivity: "Share any fears with your trusted group and/or a friend, and pray for one another!",
    reflections: ["How did God help you overcome fear today?", "What happened when you stepped out in spite of fear?"],
    prayingForSick: "Pray courageously, even trembling, knowing God has given you authority over fear."
  },
  {
    day: 15, title: "The Great Commission", theme: "Embracing the Mission!",
    worshipNote: "Thanking God invites His presence into our lives which carries His power for the miraculous",
    praiseScripture: "\"He is good! His faithful love endures forever!\" At that moment a thick cloud filled the Temple of the Lord. — 2 Chronicles 5:13-14",
    prayer: "Father, I am so grateful for the reminder in Matthew 28:19-20 that I am called to go and make disciples of all nations. I fully embrace this mission! Help me to step out confidently as I invite someone to church, Bible study, or a conference. Lead me to schools, community centers, and libraries. I lift up anyone who is sick and pray for their healing. Thank You for allowing me to be a part of Your mission. In Jesus' mighty name, amen!",
    keyScripture: "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit. — Matthew 28:19-20",
    dailyReading: "Mark 1-2",
    encouragement: "I have chosen you to be a part of My mission. Go confidently, knowing I have empowered you by My Spirit.",
    challenge: "Invite someone to church or a Bible study and share about the importance of community.",
    locationSuggestions: "Nearby schools, community centers, public libraries.",
    groupActivity: "Make a plan to reach out to friends and family who don't know Jesus. Pray with them. Lead them to Jesus.",
    reflections: ["How did it go when inviting someone to church?", "What steps can you take to make following up easier?"],
    prayingForSick: "Pray for healing as part of your mission—Jesus commanded His disciples to do the same."
  },
  {
    day: 16, title: "Living as Salt and Light", theme: "Shining Brightly in the Darkness!",
    worshipNote: "Praise helps us remember all that God has done",
    praiseScripture: "All the nations You made will come and bow before You, Lord; they will praise Your holy name. — Psalm 86:9",
    prayer: "Dear Father, As I wake up to a new day, I'm grateful for Your reminder in Matthew 5:16 to let my light shine. Today, help me to find ways to bring Your light into dark places, whether it's a prison, a rehab center, or a struggling neighborhood. I want to be a source of hope and love. I am also lifting up those who are sick. Thank You for this chance to share Your love and light. In Jesus' name, amen.",
    keyScripture: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven. — Matthew 5:16",
    dailyReading: "Mark 3-4",
    encouragement: "Today, let your actions and words be filled with the light of Christ. Shine brightly, because you are a reflection of My love in the world.",
    challenge: "Bring the light of Christ into a dark place today, whether it's visiting a prison, rehab center, or a difficult neighborhood.",
    locationSuggestions: "Prisons, rehabilitation centers, homeless shelters, challenging neighborhoods.",
    groupActivity: "Plan a community service day with friends, and use this opportunity to reach out to people.",
    reflections: ["How did you bring hope into a tough place?", "What did you learn about being My light in dark situations?"],
    prayingForSick: "Pray for God's light to break the power of sickness, pain, and disease, bringing healing and miracles."
  },
  {
    day: 17, title: "God's Power Through You", theme: "Empowered by the Spirit!",
    worshipNote: "Worship brings comfort during difficulties",
    praiseScripture: "He heals the brokenhearted and bandages their wounds. — Psalm 147:3",
    prayer: "Father, I'm so thankful for Your promise in Acts 1:8 that the Holy Spirit gives me power. It's not about my own ability but about Your Spirit working through me. Today, help me to confidently walk in that power. Show me opportunities to pray for people in public places. Give me the courage to speak Your Word over their lives, expecting to see miracles happen! Thank You for letting me be Your witness. In Jesus' name, amen!",
    keyScripture: "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses... to the ends of the earth. — Acts 1:8",
    dailyReading: "Mark 5-6",
    encouragement: "Walk in the power I've placed on the inside of you. It's not about your ability but My Spirit working through you.",
    challenge: "Pray for someone in public, declaring the power of God over their situation.",
    locationSuggestions: "Busy streets, public parks, city squares.",
    groupActivity: "Share testimonies of the power of God at work with one another over snacks, games, and fellowship, and pray together!",
    reflections: ["How did stepping out in God's power affect your confidence?", "What did you see God do when you prayed?"],
    prayingForSick: "Pray with the authority given to you through the Holy Spirit, trusting in His miracle-working power."
  },
  {
    day: 18, title: "Healing is God's Will", theme: "Embracing God's Healing Heart!",
    worshipNote: "Thankfulness encourages us to think of and serve others",
    praiseScripture: "Let the message about Christ, in all its richness, fill your lives. Sing psalms and hymns and spiritual songs to God with thankful hearts. — Colossians 3:16",
    prayer: "Dear Father, I remember Your promise from 3 John 1:2. You want us to be healthy and well. Guide me to a hospital or care home where I can pray for patients and offer them comfort. As I pray, fill me with the confidence that Your power is at work. I am trusting You to touch, change, and heal those I pray for. Thank You for the opportunity to be Your hands and feet. In Jesus' name, amen.",
    keyScripture: "Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well. — 3 John 1:2",
    dailyReading: "Mark 7-8",
    encouragement: "Remember, I desire for My people to be well. Pray knowing that healing is My heart for every person.",
    challenge: "Visit a hospital or care home, pray for patients, and offer words of comfort.",
    locationSuggestions: "Hospitals, care homes, walk-in clinics.",
    groupActivity: "Hold a prayer vigil for healing in your community.",
    reflections: ["What was your experience praying for people in need of healing?", "How did you see God's power move through your prayers?"],
    prayingForSick: "Pray confidently, knowing that healing reflects God's love and compassion."
  },
  {
    day: 19, title: "Speaking with Authority", theme: "Empowered to Speak!",
    worshipNote: "Praise can help heal emotional wounds",
    praiseScripture: "You have turned my mourning into joyful dancing. O Lord my God, I will give You thanks forever! — Psalm 30:11-12",
    prayer: "Dear Father, As I start off today, I remember that You have given me the authority to overcome fear and darkness, just like Luke 10:19. Lead me to someone struggling with fear or anxiety. Help me to share the gospel and pray confidently. I believe that Your power will flow through me and bring comfort and freedom to everyone who needs it. Thank You for allowing me to be a source of hope. In Jesus' name, amen!",
    keyScripture: "I have given you authority to trample on snakes and scorpions and to overcome all the power of the enemy; nothing will harm you. — Luke 10:19",
    dailyReading: "Mark 9-10",
    encouragement: "Speak My Word with authority, knowing that you have power over the works of the enemy.",
    challenge: "Confront fear or anxiety in someone's life by speaking the Word and praying against it.",
    locationSuggestions: "Universities, schools, counseling centers, homeless shelters.",
    groupActivity: "Come together as a group and take turns sharing a specific fear or anxiety, then engage in collective prayer.",
    reflections: ["How did using your God-given authority affect the situation?", "What impact did the power of God make when you confronted spiritual strongholds?"],
    prayingForSick: "Use your authority in Jesus' name when praying, knowing it has the power to heal and set others free."
  },
  {
    day: 20, title: "Stepping Out of Your Comfort Zone", theme: "Embracing New Opportunities!",
    worshipNote: "Worship deepens our understanding of God's nature and character",
    praiseScripture: "O Lord, what a variety of things You have made! In wisdom, You have made them all. — Psalm 104:24",
    prayer: "Dear Father, As I begin this day, I'm reminded that I can do anything through Christ who strengthens me. Help me to step out of my comfort zone. I want to explore a new part of town and share the gospel with those I meet. Guide every conversation and fill me with courage. Thank You for this amazing opportunity to connect with others and make an eternal impact. In Jesus' name!",
    keyScripture: "I can do all this through him who gives me strength. — Philippians 4:13",
    dailyReading: "Mark 11-12",
    encouragement: "Today, push past your comfort zone. I am your strength and have equipped you for every good work.",
    challenge: "Go somewhere new (like a part of town you've never visited) and start conversations about faith.",
    locationSuggestions: "New neighborhoods, neighboring towns, and city outskirts.",
    groupActivity: "Share your experiences of stepping out in faith together, highlighting favorite testimonies and greatest challenges.",
    reflections: ["How did stepping out of your comfort zone stretch your faith?", "What new opportunities did God open up?"],
    prayingForSick: "Pray with the assurance that God's power is not limited by location, comfort, or your ability. It's all His."
  },
  {
    day: 21, title: "Persistent Faith", theme: "The Power of Perseverance!",
    worshipNote: "Thankfulness leads to joy and fulfillment",
    praiseScripture: "Enter His gates with thanksgiving; go into His courts with praise. Give thanks to Him and praise His name. — Psalm 100:4",
    prayer: "Dear Father, As I begin this day, I remember that Your Word says to always pray and never give up. Help me to reach out to someone I've talked to before. I want to check in on them and show that I truly care about their journey. Even if I don't see immediate results, I will continue to pray, trusting You're always working. Thank You for allowing me to be a source of support and love. In Jesus' name, amen!",
    keyScripture: "Then Jesus told his disciples a parable to show them that they should always pray and not give up. — Luke 18:1",
    dailyReading: "Mark 13-14",
    encouragement: "Don't give up praying for those who need healing and salvation. Your persistence matters.",
    challenge: "Follow up with someone you've previously shared with and see how they're doing.",
    locationSuggestions: "Previous outreach locations; reconnect with those you've prayed for.",
    groupActivity: "Form a prayer group to consistently cover one another in prayer. Create a testimony wall to showcase God's faithfulness.",
    reflections: ["What did you learn from following up with someone?", "How did your persistence play a role in their journey?"],
    prayingForSick: "Continue to pray with boldness and unwavering faith, even when you don't see immediate results."
  },
  {
    day: 22, title: "Reaching the Lost", theme: "Sharing God's Heart for the Lost!",
    worshipNote: "Praise opens the door to God's guidance",
    praiseScripture: "O Lord, I give my life to you. Show me the right path, O Lord; point out the road for me to follow. — Psalms 25:1-5",
    prayer: "Father, I bless Your name! Today, I'm reminded that You came to seek and save the lost. Please help me to share the Gospel with someone who hasn't heard about Your love. Whether I'm on a bus, at a festival, or just running errands, guide me to the right person today. Help me learn to be more creative in reaching out. Thank You for allowing me the opportunity to be a vessel for Your love. In Jesus' name, amen.",
    keyScripture: "For the Son of Man came to seek and to save the lost. — Luke 19:10",
    dailyReading: "Mark 15-16",
    encouragement: "Remember, I came to seek and save the lost. Today, go out with My heart for those far from Me.",
    challenge: "Share the Gospel with someone you normally wouldn't approach.",
    locationSuggestions: "Public transport, festivals, gatherings, parking lots.",
    groupActivity: "Plan a community outreach event to engage with a community and win them to Jesus.",
    reflections: ["How did sharing the Gospel with someone you normally wouldn't approach impact you?", "What did you learn about reaching out to others today?"],
    prayingForSick: "Pray for God's healing as a demonstration of His love to those who don't yet know Him."
  },
  {
    day: 23, title: "Walking in Love", theme: "Love in Action!",
    worshipNote: "Worship helps strengthen us in times of weakness",
    praiseScripture: "But those who trust in the Lord will find new strength. They will soar high on wings like eagles. — Isaiah 40:31",
    prayer: "Dear Father, As I start this day, help me to walk in love just as Christ loved us. Today, I want to reach out to someone in need by sharing food, giving a ride, or lending a hand. While I'm helping others, open up opportunities for me to talk about and lead them to Jesus. Thank You for allowing me to be a vessel of Your love. In Jesus' name, amen.",
    keyScripture: "And walk in the way of love, just as Christ loved us and gave himself up for us as a fragrant offering and sacrifice to God. — Ephesians 5:2",
    dailyReading: "Luke 1-2",
    encouragement: "Let love be your motivation today. My love for others is your greatest tool in evangelism.",
    challenge: "Help someone in need today (provide food, offer a ride, etc.) and share the love of Jesus.",
    locationSuggestions: "Soup kitchens, homeless shelters, community centers.",
    groupActivity: "Host an event to share acts of kindness, such as a snack or meal, to show the love of God in action.",
    reflections: ["How did acts of love open doors for sharing the Gospel?", "What did you learn about love in action?"],
    prayingForSick: "Be an extension of God's love through prayer, bringing comfort and His power to heal and set free."
  },
  {
    day: 24, title: "Boldness in the Spirit", theme: "Empowered to be Bold!",
    worshipNote: "Thankfulness and praise transforms our hearts and minds",
    praiseScripture: "Don't copy the behavior and customs of this world, but let God transform you into a new person by changing the way you think. — Romans 12:2",
    prayer: "Dear Father, Thank You for the boldness You promise in Acts 4:31! I'm asking for that supernatural boldness to rise up as I step out to share my faith. I want to reach out to those who usually intimidate me. As I open my mouth, I trust You will guide every word. Fill me with Your presence and power. Thank You for the privilege of being Your mouthpiece. In the mighty name of Jesus, amen.",
    keyScripture: "After they prayed, the place where they were meeting was shaken. And they were all filled with the Holy Spirit and spoke the word of God boldly. — Acts 4:31",
    dailyReading: "Luke 3-4",
    encouragement: "Ask for boldness today, and I will fill you with My Spirit to speak courageously with power.",
    challenge: "Share your faith with someone who seems intimidating or who you would normally shy away from speaking to.",
    locationSuggestions: "Office buildings, restaurants, or busy business areas.",
    groupActivity: "Share a testimony of a time you were empowered by the Holy Spirit with your friend or team.",
    reflections: ["How did you feel when you asked God for boldness?", "What happened when you stepped out in faith?"],
    prayingForSick: "Pray with boldness, not hesitating to declare healing and wholeness in Jesus' name."
  },
  {
    day: 25, title: "The Good News for Everyone", theme: "Sharing the Gospel with Every Culture and Nation!",
    worshipNote: "Praise creates an atmosphere of hope and victory",
    praiseScripture: "Praise His name with dancing, accompanied by tambourines and harps. — Psalm 149:3",
    prayer: "Dear Father, Romans 1:16 reminds me of the power of the gospel! Help me to share the Good News boldly, fearlessly, and without shame. I want to connect with people from all around the world in my city—from all kinds of diverse cultures and backgrounds. As I approach each person, give me the wisdom and sensitivity to the Holy Spirit. Thank You for today's opportunity. In Jesus' name, amen.",
    keyScripture: "For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes. — Romans 1:16",
    dailyReading: "Luke 5-6",
    encouragement: "The Gospel is for everyone. Share it boldly, without hesitation, fear, or shame.",
    challenge: "Approach someone from a different culture or background and share the Good News.",
    locationSuggestions: "Multicultural neighborhoods, markets, malls, or festivals.",
    groupActivity: "Create an infographic or video explaining the Gospel message, then share on social media.",
    reflections: ["What did you learn about sharing the Gospel across cultural boundaries?", "How did the person respond to the message?"],
    prayingForSick: "Pray for the healing power of God to transcend every barrier, whether cultural or spiritual."
  },
  {
    day: 26, title: "The Miracle Worker", theme: "Limitless God!",
    worshipNote: "Worship places God in the highest place in our lives",
    praiseScripture: "You are worthy, O Lord our God, to receive glory and honor and power. — Revelation 4:11",
    prayer: "Dear Father, Thank You for Hebrews 13:8 which says You are the same yesterday, today, and forever. You are the Miracle Worker! Today, I am believing for miracles! I will step out in faith. Help me to pray specifically for someone who needs a miracle. As I pray, help me to see Your power touching and changing their lives. Thank You for the opportunity to be a vessel through which the world can experience You. In Jesus' name, amen.",
    keyScripture: "Jesus Christ is the same yesterday and today and forever. — Hebrews 13:8",
    dailyReading: "Luke 7-8",
    encouragement: "I am still the Miracle Worker. I am the same yesterday, today, and forever. Believe for the miraculous today.",
    challenge: "Pray specifically for a miracle in someone's life, whether healing, provision, or deliverance.",
    locationSuggestions: "Hospitals, business areas, shelters.",
    groupActivity: "Organize a potluck, testimony, or games night.",
    reflections: ["Did you see the power of God at work today?", "How did praying for miracles stretch your faith?"],
    prayingForSick: "Pray knowing that it is Jesus working to heal and perform miracles through you today."
  },
  {
    day: 27, title: "Sowing Seeds", theme: "Little is Much in God's Hands!",
    worshipNote: "Thanking God reminds us of His faithfulness",
    praiseScripture: "Give thanks to the Lord, for He is good! His faithful love endures forever. — Psalm 136:1",
    prayer: "Dear Father, As I start this day, I'm reminded of Galatians 6:9, which encourages us not to tire of doing good. Help me to engage in multiple conversations today, even if they seem brief. I want to sow seeds of faith in every interaction. I am trusting for every kind word, prayer, and act of kindness to leave an eternal impact. Thank You for the opportunity! In Jesus' name, amen.",
    keyScripture: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. — Galatians 6:9",
    dailyReading: "Luke 9-10",
    encouragement: "Every conversation, every prayer, every act of kindness is a seed sown. Trust Me for the harvest.",
    challenge: "Talk to multiple people today, even if it feels like small interactions—sow seeds of faith.",
    locationSuggestions: "Busy streets, shopping centers, public transport.",
    groupActivity: "Create a prayer wall for community needs and people witnessed to.",
    reflections: ["How did you see God use even the smallest interactions for His purpose?", "What seeds were you able to sow today?"],
    prayingForSick: "Pray, trusting that every prayer is a seed that will grow into a testimony and reap a mighty harvest."
  },
  {
    day: 28, title: "The Power of Prayer", theme: "Faith Creates Reality!",
    worshipNote: "Praise can change our perspective on life",
    praiseScripture: "Praise the Lord! Yes, give praise, O servants of the Lord. Praise the name of the Lord! — Psalm 113:1",
    prayer: "Dear Father, Today, I'm reminded of James 5:16: the prayer of a righteous person is powerful and effective. Today, I lift up everyone I've talked to this month. Help me to remember each name and situation as I pray. Show me Your heart for each person. Help me see each person as You see them. I believe they will continue to experience Your life-changing power because You finish what You start. In Jesus' name, amen.",
    keyScripture: "The prayer of a righteous person is powerful and effective. — James 5:16",
    dailyReading: "Luke 11-12",
    encouragement: "Never underestimate the power of prayer. Trust Me, and see how I work through you.",
    challenge: "Spend time praying specifically for those you have spoken to this month, lifting them up by name.",
    locationSuggestions: "Prayer rooms, quiet parks, your personal space.",
    groupActivity: "Organize a revival night of worship and prayer.",
    reflections: ["How did focused prayer change your perspective on outreach?", "Did you feel a renewed sense of God's heart for those you prayed for?"],
    prayingForSick: "Pray with fervency and persistence, trusting My power to touch lives and make a difference."
  },
  {
    day: 29, title: "Revival Starts with You", theme: "Empowered by God, Changing the World!",
    worshipNote: "Worship is a form of spiritual warfare against negativity",
    praiseScripture: "At the very moment they began to sing and give praise, the Lord caused the armies of Ammon, Moab, and Mount Seir to start fighting among themselves. — 2 Chronicles 20:22",
    prayer: "Father, Your Word reminds us in 2 Chronicles 7:14 that true revival starts within our hearts. Help me to humble myself and earnestly seek Your presence above everything else. Lord, I ask for a fresh outpouring of Your fire to reignite a passion for Your Word and presence within me. Transform my heart and mind so that I will shine bright as a beacon of hope. Make me a vessel of change in my generation. In Jesus' name, amen.",
    keyScripture: "If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven and I will forgive their sin and heal their land. — 2 Chronicles 7:14",
    dailyReading: "Luke 13-14",
    encouragement: "Revival begins with YOU, in your heart. As you are transformed, you will see transformation everywhere around you.",
    challenge: "Pray for revival in your city, starting with yourself. Ask God to ignite a passion in your heart.",
    locationSuggestions: "Churches, community prayer gatherings, at home.",
    groupActivity: "Organize a night to invite people you have witnessed to. Draw their names amongst yourselves and surprise them with gifts to bless them.",
    reflections: ["How did praying for revival affect your desire to reach out?", "What areas of your own heart need revival?"],
    prayingForSick: "Let your prayers for healing and miracles be part of a larger cry to see revival explode in your city and nation!"
  },
  {
    day: 30, title: "Celebrating Victory", theme: "30 Days of Impact: Celebrating Our Victories for the Kingdom!",
    worshipNote: "Thankfulness creates a culture of celebration and joy",
    praiseScripture: "Praise the Lord! Sing to the Lord a new song. Sing His praises in the assembly of the faithful. — Psalms 149:1",
    prayer: "Dear Father, As I reflect on Psalm 126:3, I want to thank You for the incredible things You have done in my life. Today, I celebrate every victory, every soul saved, every prayer answered, and every step of faith I have taken. I give You every ounce of glory. Guide me as I gather with friends or my team to share testimonies of Your goodness this month. Thank You for every single healing and miracle. I give You all the praise and glory. In Jesus' name, amen.",
    keyScripture: "The Lord has done great things for us, and we are filled with joy. — Psalm 126:3",
    dailyReading: "Luke 15-16",
    encouragement: "Celebrate all the victories! Every soul saved, every prayer, every step of faith is a victory in the advancement of the Kingdom of God. Well done!",
    challenge: "Gather with your friend or team and share testimonies of what God has done this month.",
    locationSuggestions: "Church, home group, restaurant.",
    groupActivity: "Gather with your friends or team, and have each member share about the things they experienced and accomplished throughout the challenge.",
    reflections: ["What was the greatest testimony you saw this month?", "How has your faith grown over the past 30 days?"],
    prayingForSick: "Give God praise and thanks for every healing, miracle, and answered prayer you've seen."
  }
];
